spring:
  application:
    name: FinanceDataService
finance:
  data:
    base-dir: data
alpha-vantage:
  base-url: https://www.alphavantage.co
  api-key: W0I6NZZKXFK8R7V2
twelve-data:
  base-url: https://api.twelvedata.com
  api-key: 58e87b1c442a464f8c10e61a77db7871
  interval: 1day
  enabled: true
  request-delay-ms: 500
