apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-data-service.fullname" . }}
  labels:
    {{- include "finance-data-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (.Values.service.nodePort) (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "finance-data-service.selectorLabels" . | nindent 4 }}
